//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ffffffffff
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверка денег.
    /// </summary>
    // *** Start programmer edit section *** (ПроверкаДенег CustomAttributes)

    // *** End programmer edit section *** (ПроверкаДенег CustomAttributes)
    [AutoAltered()]
    [Caption("Проверка денег")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроверкаДенегE", new string[] {
            "ДатаПроверки as \'Дата проверки\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'",
            "ДенежныйЯщик as \'Денежный ящик\'",
            "КоличествоДенег as \'Количество денег\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ПроверкаДенегE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ПроверкаДенегL", new string[] {
            "ДатаПроверки as \'Дата проверки\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'"})]
    public class ПроверкаДенег : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПроверки = System.DateTime.Now;
        
        private IIS.Ffffffffff.Ящик fДенежныйЯщик;
        
        private double fКоличествоДенег;
        
        private IIS.Ffffffffff.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ПроверкаДенег CustomMembers)

        // *** End programmer edit section *** (ПроверкаДенег CustomMembers)

        
        /// <summary>
        /// ДатаПроверки.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаДенег.ДатаПроверки CustomAttributes)

        // *** End programmer edit section *** (ПроверкаДенег.ДатаПроверки CustomAttributes)
        public virtual System.DateTime ДатаПроверки
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаДенег.ДатаПроверки Get start)

                // *** End programmer edit section *** (ПроверкаДенег.ДатаПроверки Get start)
                System.DateTime result = this.fДатаПроверки;
                // *** Start programmer edit section *** (ПроверкаДенег.ДатаПроверки Get end)

                // *** End programmer edit section *** (ПроверкаДенег.ДатаПроверки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаДенег.ДатаПроверки Set start)

                // *** End programmer edit section *** (ПроверкаДенег.ДатаПроверки Set start)
                this.fДатаПроверки = value;
                // *** Start programmer edit section *** (ПроверкаДенег.ДатаПроверки Set end)

                // *** End programmer edit section *** (ПроверкаДенег.ДатаПроверки Set end)
            }
        }
        
        /// <summary>
        /// ДенежныйЯщик.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаДенег.ДенежныйЯщик CustomAttributes)

        // *** End programmer edit section *** (ПроверкаДенег.ДенежныйЯщик CustomAttributes)
        public virtual IIS.Ffffffffff.Ящик ДенежныйЯщик
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаДенег.ДенежныйЯщик Get start)

                // *** End programmer edit section *** (ПроверкаДенег.ДенежныйЯщик Get start)
                IIS.Ffffffffff.Ящик result = this.fДенежныйЯщик;
                // *** Start programmer edit section *** (ПроверкаДенег.ДенежныйЯщик Get end)

                // *** End programmer edit section *** (ПроверкаДенег.ДенежныйЯщик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаДенег.ДенежныйЯщик Set start)

                // *** End programmer edit section *** (ПроверкаДенег.ДенежныйЯщик Set start)
                this.fДенежныйЯщик = value;
                // *** Start programmer edit section *** (ПроверкаДенег.ДенежныйЯщик Set end)

                // *** End programmer edit section *** (ПроверкаДенег.ДенежныйЯщик Set end)
            }
        }
        
        /// <summary>
        /// КоличествоДенег.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаДенег.КоличествоДенег CustomAttributes)

        // *** End programmer edit section *** (ПроверкаДенег.КоличествоДенег CustomAttributes)
        public virtual double КоличествоДенег
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаДенег.КоличествоДенег Get start)

                // *** End programmer edit section *** (ПроверкаДенег.КоличествоДенег Get start)
                double result = this.fКоличествоДенег;
                // *** Start programmer edit section *** (ПроверкаДенег.КоличествоДенег Get end)

                // *** End programmer edit section *** (ПроверкаДенег.КоличествоДенег Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаДенег.КоличествоДенег Set start)

                // *** End programmer edit section *** (ПроверкаДенег.КоличествоДенег Set start)
                this.fКоличествоДенег = value;
                // *** Start programmer edit section *** (ПроверкаДенег.КоличествоДенег Set end)

                // *** End programmer edit section *** (ПроверкаДенег.КоличествоДенег Set end)
            }
        }
        
        /// <summary>
        /// Проверка денег.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаДенег.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ПроверкаДенег.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Ffffffffff.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаДенег.Сотрудники Get start)

                // *** End programmer edit section *** (ПроверкаДенег.Сотрудники Get start)
                IIS.Ffffffffff.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ПроверкаДенег.Сотрудники Get end)

                // *** End programmer edit section *** (ПроверкаДенег.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаДенег.Сотрудники Set start)

                // *** End programmer edit section *** (ПроверкаДенег.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ПроверкаДенег.Сотрудники Set end)

                // *** End programmer edit section *** (ПроверкаДенег.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроверкаДенегE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаДенегE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаДенегE", typeof(IIS.Ffffffffff.ПроверкаДенег));
                }
            }
            
            /// <summary>
            /// "ПроверкаДенегL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаДенегL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаДенегL", typeof(IIS.Ffffffffff.ПроверкаДенег));
                }
            }
        }
    }
}
