//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ffffffffff
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ящик.
    /// </summary>
    // *** Start programmer edit section *** (Ящик CustomAttributes)

    // *** End programmer edit section *** (Ящик CustomAttributes)
    public enum Ящик
    {
        
        // *** Start programmer edit section *** (Ящик.ЗабратьДеньги CustomAttributes)

        // *** End programmer edit section *** (Ящик.ЗабратьДеньги CustomAttributes)
        [Caption("ЗабратьДеньги")]
        ЗабратьДеньги,
        
        // *** Start programmer edit section *** (Ящик.ДобавитьДеньги CustomAttributes)

        // *** End programmer edit section *** (Ящик.ДобавитьДеньги CustomAttributes)
        [Caption("ДобавитьДеньги")]
        ДобавитьДеньги,
    }
}
